### ISSUE TITLE
不成功

### ISSUE THREAD

**Issue by androidcn** [2van/baidumap-to-amap#1]
`get detail fail 

query by keywords fail

get detail fail

[
  '荣超商务中心-地下车库 | 深圳市',
  ... 102 more items
]

0 202`

**Comment by androidcn** [comment]
这些都配置好

配置config.js下的cookie，token，转移的数量规模

**Comment by 2van** [comment]
这些都是用自己的，另外失败有可能是被反爬虫了。

**Comment by androidcn** [comment]
> 这些都是用自己的，另外失败有可能是被反爬虫了。

我都是用自己的，

后来高德，一直显示，网络错误，刷新不了

**Comment by 2van** [comment]
高德对于频繁的请求会有验证弹窗，需要手动操作解除，所以该项目遇到这种情况用不了

**Comment by androidcn** [comment]
> 高德对于频繁的请求会有验证弹窗，需要手动操作解除，所以该项目遇到这种情况用不了

能否 一条一条 人工确认 来做，100个以内，用这个系统 其实很轻松

**Comment by androidcn** [comment]
百度获取数据没问题，肯定 是高德反爬虫，如果我们一条一条添加 就 应该不会 有问题

**Comment by 2van** [comment]
如果人工一条一条来做，就等于直接在高德手动添加了一样。而且实际情况是高德发现你频繁请求（手动正常访问）就会弹验证

**Comment by androidcn** [comment]
已经很不错了，
我不熟悉nodejs，尝试添加prompt，命令行添加不成功，方便帮我改一下一条一条我来自己确认搜索，搜索成功后，自己点添加，时间自己来定，相当于自己一个一个添加，快速模拟真实情况。批量请求肯定就反爬虫了

**Comment by 2van** [comment]
可以，我晚上改下

**Comment by androidcn** [comment]
> 可以，我晚上改下

Thanks

**Comment by 2van** [comment]
昨晚改了忘提交了，你可以自己试着改下等待时间，改成10秒就不会被反爬虫。被反爬虫后去网页解除验证弹窗再使用新的cookie和token即可。

**Comment by 2van** [comment]
await TimeAwait(10e3);

**Comment by androidcn** [comment]
> await TimeAwait(10e3);

设置了 15e3

还是会 飞快的 提示 fail

**Comment by androidcn** [comment]
> 昨晚改了忘提交了，你可以自己试着改下等待时间，改成10秒就不会被反爬虫。被反爬虫后去网页解除验证弹窗再使用新的cookie和token即可。

能否 重新递交?

修改config 后
两次npm i
node index.js

速度是飞快的,
